/*
 * API Pagamentos
 * Este é um exemplo de serviço de validação de pagamentos
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiPagamentos) {
      root.ApiPagamentos = {};
    }
    root.ApiPagamentos.Authorization = factory(root.ApiPagamentos.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Authorization model module.
   * @module model/Authorization
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Authorization</code>.
   * @alias module:model/Authorization
   * @class
   * @param id {Number} Identificador da compra
   * @param code {String} Codigo retornado da autorização da compra
   */
  var exports = function(id, code) {
    this.id = id;
    this.code = code;
  };

  /**
   * Constructs a <code>Authorization</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Authorization} obj Optional instance to populate.
   * @return {module:model/Authorization} The populated <code>Authorization</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }

  /**
   * Identificador da compra
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * Codigo retornado da autorização da compra
   * @member {String} code
   */
  exports.prototype.code = undefined;

  return exports;

}));
