/*
 * API Pagamentos
 * Este é um exemplo de serviço de validação de pagamentos
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiPagamentos) {
      root.ApiPagamentos = {};
    }
    root.ApiPagamentos.Status = factory(root.ApiPagamentos.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Status model module.
   * @module model/Status
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Status</code>.
   * @alias module:model/Status
   * @class
   * @param status {module:model/Status.StatusEnum} Retorno do status do pedido
   */
  var exports = function(status) {
    this.status = status;
  };

  /**
   * Constructs a <code>Status</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Status} obj Optional instance to populate.
   * @return {module:model/Status} The populated <code>Status</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }

  /**
   * Retorno do status do pedido
   * @member {module:model/Status.StatusEnum} status
   */
  exports.prototype.status = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "aguardando pagamento do boleto"
     * @const
     */
    aguardandoPagamentoDoBoleto: "aguardando pagamento do boleto",

    /**
     * value: "aguardando aprovacao do cartao"
     * @const
     */
    aguardandoAprovacaoDoCartao: "aguardando aprovacao do cartao",

    /**
     * value: "aguardando autorizacao do banco"
     * @const
     */
    aguardandoAutorizacaoDoBanco: "aguardando autorizacao do banco",

    /**
     * value: "autorizado"
     * @const
     */
    autorizado: "autorizado"
  };

  return exports;

}));
