/*
 * API Pagamentos
 * Este é um exemplo de serviço de validação de pagamentos
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiPagamentos);
  }
}(this, function(expect, ApiPagamentos) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiPagamentos.ValidationApi();
  });

  describe('(package)', function() {
    describe('ValidationApi', function() {
      describe('antifraud', function() {
        it('should call antifraud successfully', function(done) {
          // TODO: uncomment, update parameter values for antifraud call and complete the assertions
          /*
          var authorization = "authorization_example";
          var code = new ApiPagamentos.Authorization();
          code.id = ;
          code.code = "";

          instance.antifraud(authorization, code, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('complete', function() {
        it('should call complete successfully', function(done) {
          // TODO: uncomment, update parameter values for complete call and complete the assertions
          /*
          var authorization = "authorization_example";
          var code = new ApiPagamentos.Authorization();
          code.id = ;
          code.code = "";

          instance.complete(authorization, code, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
